package com.deployforge.api.event;

public enum DeploymentIntentEventType {
    ARTIFACT_REGISTERED,
    ARTIFACT_EVIDENCE_ADDED,
    PLAN_CREATED,
    PLAN_IDEMPOTENT_REPLAYED,
    PLAN_IDEMPOTENCY_CONFLICT,
    PLAN_CANCELLED,
    PLAN_ABORTED,
    ENVIRONMENT_STATE_PLANNED,
    DEPLOYABILITY_CHECK_FAILED,
    PROMOTION_RULE_UPSERTED,
    PROMOTION_EVIDENCE_RECORDED,
    PROTECTED_POLICY_UPSERTED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    APPROVAL_EXPIRED,
    DEPLOYMENT_LOCK_ACQUIRED,
    DEPLOYMENT_LOCK_RELEASED,
    DEPLOYMENT_LOCK_EXPIRED,
    DEPLOYMENT_LOCK_STALE_RELEASED,
    OVERRIDE_RECORDED,
    GATE_DEFINITION_CREATED,
    GATE_EVALUATED,
    GATE_OVERRIDDEN,
    GATE_RERUN_REQUESTED
}
