package com.deployforge.api.event;

public enum DeploymentIntentEventType {
    ARTIFACT_REGISTERED,
    ARTIFACT_EVIDENCE_ADDED,
    PLAN_CREATED,
    PLAN_IDEMPOTENT_REPLAYED,
    PLAN_IDEMPOTENCY_CONFLICT,
    PLAN_CANCELLED,
    ENVIRONMENT_STATE_PLANNED,
    DEPLOYABILITY_CHECK_FAILED
}
